### ISSUE TITLE
registration, login

### ISSUE THREAD

**Issue by nataliakushnir** [sanarkk/django-website#1]
сторінка реєстрації: first_name, last_name, email, номер телефону
сторінка логіну з виведенням помилок форми

use django-allauth for static, django-rest-auth for rest framework

redirect after login to dashboard page (login required - use mixin)

dashboard leave empty

**Comment by sanarkk** [comment]
Developed authentication with Django all-auth.
Login form shows errors if user enters data incorectly.
After user registration/login - code redirects user to dashboard page.
Dashboard page is empty and has permission mixin(LoginRequiredMixin).
